name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run testing examples
        run: cd src && make test && ./a.out
      - name: clean object files
        run: cd src && make clean
